language: node_js
node_js:
- '8'
branches:
  only:
  - master
deploy:
  provider: heroku
  api_key:
    secure: "Vje3Xf0oYLYDMvcuphotsPbt0TSOiSFfxPkxo45AyoqnC2iHlf90dvg/6SneNIIprWy28K1MRosSIuwO3K07KE2B/TyRgh5tefUbORz94eNsEAQdrbkkhLXPFxAmKfdPJdlOWzhL8gtSCmbpCoKHSmXwdVA/VALXbcjt
LSY/+B8QZqAp0UFtSHk8M13vanBoqVi0EKyaXwVruozmP2w0K9c+nnF2zceSGekDlQHNtNPkB0KEAJ/cc7HusnSXCuXUqj5f/l2YMoexP7o5mmruCyJzTYtHLf2Lq02ucR5Jw26t5WCIc09xqcSTb7L2umXFl45JJgrEpfn9BaJdn5c
vVAaCC/kqQPkpwu56DAAZIldqi9pBFf+6/xFQXL9460BXWRX+8Pt7OF+Tr4TzMar202FWVZZJKVrrzojv1QabP4/Jwj6zGl3W0rQAQU7CwptC7u4GvsMWuaulxN4iW+uJp+iisLbeuf10mMVrkizxYI2Yf9w728ZyCOERUlvY9ei5CV
iVNq22Qh6ueUXFwHkCwIyCHgcvdzCr2kuQIVxKI2QNoGRY9n73Hy2OBVKW2Y2if9nTueFvNtXnYd+l/peEZ9OURkpCL25RmMVt93y2irFzrzwZLQ3uD5m9npLqi8Gfy+e1btRK+xPx/omN4uMnSVPbrgeLEWhRlsFdG3UHu7M="
app: rest-todo-api
