language: node_js
node_js:
- '8'
branches:
  only:
  - master
deploy:
  provider: heroku
  api_key:
    secure: "1aWW2ZXtq23rk9qMRNG944Wn8adav49cp+XjUcZSmknQGPIgQg5iODcQwt6zq8PcBgMoZyQ3z+xF080hWibuK9RO7WBBW0Jy+Tuya3Xqna1fjQwBdS21blErYZbaA3yT0/YRfQNPiWUdk6XEZmc1Nfke6NVy7ro8fjxL
K2uCP8Vd4UeK61h9hHVOpfp2+zhvj1JHlq6xW54V6n5UDpdvWnj9XHAn+ZbbNfbyfHXlJPmX+AHlDB0pNHj82BQ8Op/2MxEtzyW36jB+pBMqDRi0kNB13o3kY5S5Gu9gyys9gq+ue5esjxU/NZjvtAnrgevKJyj7xAJ0SJqBQAjczzJ
36Mo/DFR4wwfQ8nPXNXobC3sKu7T2ypfJnoAyEW/F8FWELqR4Wb9cqvMUoAByUY05JL+i2izwmW0mhVaDJPbt6LXygBwbVcKSDxCarakk3P+ohVMBLzDYnJOttcbTKyLc2XBAYWvqwTsoZo17X5GVPPewUaN1zlLFcxZh6NYSUC40Eh
PCMtQyihHCT4w+wlb7UNw1y4HYsFxwWY43Dy/Zfc7nj7CCFCCHuc9FGXXNw+JhX6gFCGhkiipYThsTYyMa1Qnt6m4tWNxBPXeMJBiO4hDMCx2RITzrMl1NDzD8h+qeWuVz1kwZUBzk6CT2w/0J2sGChAVOWD42CQh0cWdozyk="
app: rest-todo-api